<?php

return [
    'Ensino Médio' => [
        'Matemática',
        'Português',
        'História',
        'Geografia',
        'Física',
        'Química',
    ],
    'Direito' => [
        'Direito Constitucional',
        'Direito Penal',
        'Direito Civil',
        'Direito Administrativo',
        'Direito Trabalhista',
        'Direito Tributário',
    ],
    'Medicina' => [
        'Anatomia',
        'Fisiologia',
        'Farmacologia',
        'Patologia',
        'Clínica Médica',
        'Cirurgia',
    ],
    'Economia' => [
        'Microeconomia',
        'Macroeconomia',
        'Economia Internacional',
        'Econometria',
        'Desenvolvimento Econômico',
        'Finanças Públicas',
    ],
    'Sociologia' => [
        'Teoria Sociológica',
        'Métodos de Pesquisa',
        'Sociologia da Educação',
        'Sociologia Urbana',
        'Sociologia do Trabalho',
        'Sociologia da Família',
    ],
    'Psicologia' => [
        'Psicologia Clínica',
        'Psicologia Social',
        'Psicologia do Desenvolvimento',
        'Neuropsicologia',
        'Psicologia Organizacional',
        'Psicopatologia',
    ],
    'Educação' => [
        'Didática',
        'Psicologia da Educação',
        'História da Educação',
        'Política Educacional',
        'Educação Inclusiva',
        'Tecnologias Educacionais',
    ],
    'Tecnologia' => [
        'Programação',
        'Redes de Computadores',
        'Banco de Dados',
        'Engenharia de Software',
        'Inteligência Artificial',
        'Segurança da Informação',
    ],
    'Finanças' => [
        'Contabilidade',
        'Gestão Financeira',
        'Mercado de Capitais',
        'Planejamento Financeiro',
        'Auditoria',
        'Análise de Investimentos',
    ],
    'Filosofia' => [
        'História da Filosofia',
        'Ética',
        'Lógica',
        'Epistemologia',
        'Metafísica',
        'Filosofia Política',
    ],
    'Educação Física' => [
        'Anatomia',
        'Fisiologia do Exercício',
        'Biomecânica',
        'Treinamento Desportivo',
        'Psicologia do Esporte',
        'Educação Física Escolar',
    ],
    'Segurança Pública' => [
        'Criminologia',
        'Direito Penal',
        'Direito Processual Penal',
        'Investigação Criminal',
        'Policiamento Ostensivo',
        'Gestão de Segurança Pública',
    ],
    'Saúde Pública' => [
        'Epidemiologia',
        'Saúde Coletiva',
        'Gestão em Saúde',
        'Políticas de Saúde',
        'Promoção da Saúde',
        'Vigilância Sanitária',
    ],
    'Administração' => [
        'Teoria Geral da Administração',
        'Gestão de Pessoas',
        'Marketing',
        'Finanças Corporativas',
        'Planejamento Estratégico',
        'Empreendedorismo',
    ],
    'Contabilidade' => [
        'Contabilidade Geral',
        'Contabilidade de Custos',
        'Contabilidade Tributária',
        'Contabilidade Gerencial',
        'Auditoria',
        'Perícia Contábil',
    ],
    'Engenharia Civil' => [
        'Cálculo Estrutural',
        'Materiais de Construção',
        'Hidráulica',
        'Geotécnica',
        'Transporte e Logística',
        'Construção Civil',
    ],
    'Engenharia Ambiental' => [
        'Gestão Ambiental',
        'Saneamento Ambiental',
        'Ecologia',
        'Impacto Ambiental',
        'Recuperação de Áreas Degradadas',
        'Tecnologia Ambiental',
    ],
    'Engenharia da Computação' => [
        'Algoritmos',
        'Arquitetura de Computadores',
        'Redes de Computadores',
        'Sistemas Operacionais',
        'Inteligência Artificial',
        'Segurança da Informação',
    ],
    'Engenharia Elétrica' => [
        'Circuitos Elétricos',
        'Eletromagnetismo',
        'Sistemas de Potência',
        'Eletrônica',
        'Máquinas Elétricas',
        'Instalações Elétricas',
    ],
    'Engenharia Mecatrônica' => [
        'Robótica',
        'Controle e Automação',
        'Sistemas Microprocessados',
        'Eletrônica de Potência',
        'Mecânica dos Sólidos',
        'Sistemas Térmicos',
    ],
    'Engenharia Mecânica' => [
        'Termodinâmica',
        'Mecânica dos Fluidos',
        'Resistência dos Materiais',
        'Processos de Fabricação',
        'Elementos de Máquinas',
        'Projeto Mecânico',
    ],
    'Biologia' => [
        'Genética',
        'Microbiologia',
        'Zoologia',
        'Botânica',
        'Ecologia',
        'Fisiologia Animal',
    ],
    'Química' => [
        'Química Geral',
        'Química Orgânica',
        'Química Inorgânica',
        'Físico-Química',
        'Bioquímica',
        'Química Analítica',
    ],
    'Física' => [
        'Mecânica Clássica',
        'Eletromagnetismo',
        'Termodinâmica',
        'Física Quântica',
        'Física Experimental',
        'Astrofísica',
    ],
    'Matemática' => [
        'Álgebra Linear',
        'Cálculo Diferencial e Integral',
        'Geometria Analítica',
        'Estatística',
        'Matemática Discreta',
        'Análise Real',
    ],
    'História' => [
        'História Antiga',
        'História Medieval',
        'História Moderna',
        'História Contemporânea',
        'História do Brasil',
        'História da América',
    ],
    'Geografia' => [
        'Geografia Física',
        'Geografia Humana',
        'Cartografia',
        'Geopolítica',
        'Climatologia',
        'Biogeografia',
    ],
    'Artes' => [
        'História da Arte',
        'Artes Visuais',
        'Teatro',
        'Música',
        'Dança',
        'Literatura',
    ],
    'Literatura' => [
        'Teoria da Literatura',
        'Literatura Brasileira',
        'Literatura Portuguesa',
        'Literatura Inglesa',
        'Literatura Comparada',
        'Crítica Literária',
    ],
    'Música' => [
        'Teoria Musical',
        'História da Música',
        'Harmonia',
        'Composição',
        'Regência',
        'Performance',
    ],
    'Ciência Política' => [
        'Teoria Política',
        'Política Comparada',
        'Políticas Públicas',
        'Relações Internacionais',
        'Sistemas de Governo',
        'Filosofia Política',
    ],
    'Arquitetura' => [
        'História da Arquitetura',
        'Projeto Arquitetônico',
        'Urbanismo',
        'Tecnologia da Construção',
        'Conforto Ambiental',
        'Paisagismo',
    ],
    'Comunicação' => [
        'Teorias da Comunicação',
        'Jornalismo',
        'Publicidade e Propaganda',
        'Relações Públicas',
        'Comunicação Organizacional',
        'Mídias Digitais',
    ],
];
