<?php

return [
    'Ensino Médio',
    'Direito',
    'Medicina',
    'Economia',
    'Sociologia',
    'Psicologia',
    'Educação',
    'Filosofia',
    'Educação Física',
    'Segurança Pública',
    'Saúde Pública',
    'Administração',
    'Contabilidade',
    'Engenharia Civil',
    'Engenharia Ambiental',
    'Engenharia da Computação',
    'Engenharia Elétrica',
    'Engenharia Mecatrônica',
    'Engenharia Mecânica',
    'Biologia',
    'Química',
    'Física',
    'Matemática',
    'História',
    'Geografia',
    'Artes',
    'Literatura',
    'Música',
    'Ciência Política',
    'Arquitetura',
    'Comunicação',
];
