<?php

return [
    'Matemática',
    'Português',
    'História',
    'Geografia',
    'Física',
    'Química',
    'Direito Constitucional',
    'Direito Penal',
    'Direito Civil',
    'Direito Administrativo',
    'Direito Trabalhista',
    'Direito Tributário',
    'Anatomia',
    'Fisiologia',
    'Farmacologia',
    'Patologia',
    'Clínica Médica',
    'Cirurgia',
    'Microeconomia',
    'Macroeconomia',
    'Economia Internacional',
    'Econometria',
    'Desenvolvimento Econômico',
    'Finanças Públicas',
    'Teoria Sociológica',
    'Métodos de Pesquisa',
    'Sociologia da Educação',
    'Sociologia Urbana',
    'Sociologia do Trabalho',
    'Sociologia da Família',
    'Psicologia Clínica',
    'Psicologia Social',
    'Psicologia do Desenvolvimento',
    'Neuropsicologia',
    'Psicologia Organizacional',
    'Psicopatologia',
    'Didática',
    'Psicologia da Educação',
    'História da Educação',
    'Política Educacional',
    'Educação Inclusiva',
    'Tecnologias Educacionais',
    'História da Filosofia',
    'Ética',
    'Lógica',
    'Epistemologia',
    'Metafísica',
    'Filosofia Política',
    'Fisiologia do Exercício',
    'Biomecânica',
    'Treinamento Desportivo',
    'Psicologia do Esporte',
    'Educação Física Escolar',
    'Criminologia',
    'Direito Processual Penal',
    'Investigação Criminal',
    'Policiamento Ostensivo',
    'Gestão de Segurança Pública',
    'Epidemiologia',
    'Saúde Coletiva',
    'Gestão em Saúde',
    'Políticas de Saúde',
    'Promoção da Saúde',
    'Vigilância Sanitária',
    'Teoria Geral da Administração',
    'Gestão de Pessoas',
    'Marketing',
    'Finanças Corporativas',
    'Planejamento Estratégico',
    'Empreendedorismo',
    'Contabilidade Geral',
    'Contabilidade de Custos',
    'Contabilidade Tributária',
    'Contabilidade Gerencial',
    'Auditoria',
    'Perícia Contábil',
    'Cálculo Estrutural',
    'Materiais de Construção',
    'Hidráulica',
    'Geotécnica',
    'Transporte e Logística',
    'Construção Civil',
    'Gestão Ambiental',
    'Saneamento Ambiental',
    'Impacto Ambiental',
    'Recuperação de Áreas Degradadas',
    'Tecnologia Ambiental',
    'Algoritmos',
    'Arquitetura de Computadores',
    'Redes de Computadores',
    'Sistemas Operacionais',
    'Inteligência Artificial',
    'Segurança da Informação',
    'Circuitos Elétricos',
    'Eletromagnetismo',
    'Sistemas de Potência',
    'Eletrônica',
    'Máquinas Elétricas',
    'Instalações Elétricas',
    'Robótica',
    'Controle e Automação',
    'Sistemas Microprocessados',
    'Eletrônica de Potência',
    'Mecânica dos Sólidos',
    'Sistemas Térmicos',
    'Mecânica dos Fluidos',
    'Resistência dos Materiais',
    'Processos de Fabricação',
    'Elementos de Máquinas',
    'Projeto Mecânico',
    'Genética',
    'Microbiologia',
    'Zoologia',
    'Botânica',
    'Ecologia',
    'Fisiologia Animal',
    'Química Geral',
    'Química Orgânica',
    'Química Inorgânica',
    'Físico-Química',
    'Bioquímica',
    'Química Analítica',
    'Mecânica Clássica',
    'Termodinâmica',
    'Física Quântica',
    'Física Experimental',
    'Astrofísica',
    'Álgebra Linear',
    'Cálculo Diferencial e Integral',
    'Geometria Analítica',
    'Estatística',
    'Matemática Discreta',
    'Análise Real',
    'História Antiga',
    'História Medieval',
    'História Moderna',
    'História Contemporânea',
    'História do Brasil',
    'História da América',
    'Geografia Física',
    'Geografia Humana',
    'Cartografia',
    'Geopolítica',
    'Climatologia',
    'Biogeografia',
    'História da Arte',
    'Artes Visuais',
    'Teatro',
    'Música',
    'Dança',
    'Literatura',
    'Teoria da Literatura',
    'Literatura Brasileira',
    'Literatura Portuguesa',
    'Literatura Inglesa',
    'Literatura Comparada',
    'Crítica Literária',
    'Teoria Musical',
    'História da Música',
    'Harmonia',
    'Composição',
    'Regência',
    'Performance',
    'Teoria Política',
    'Política Comparada',
    'Políticas Públicas',
    'Relações Internacionais',
    'Sistemas de Governo',
    'História da Arquitetura',
    'Projeto Arquitetônico',
    'Urbanismo',
    'Tecnologia da Construção',
    'Conforto Ambiental',
    'Paisagismo',
    'Teorias da Comunicação',
    'Jornalismo',
    'Publicidade e Propaganda',
    'Relações Públicas',
    'Comunicação Organizacional',
    'Mídias Digitais',
];
